name: Windows Native Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: build (${{ matrix.arch }})
    runs-on: ${{ matrix.runs_on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            runs_on: windows-2025
          - arch: arm64
            runs_on: windows-11-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup MSVC DevCmd (${{ matrix.arch }})
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Configure (CMake NMake)
        run: |
          cmake -S src/c -B build -G "NMake Makefiles" -DUNICODE=ON
        shell: bash

      - name: Build (Release)
        run: |
          cmake --build build --config Release --verbose
        shell: bash

      - name: List outputs
        run: |
          ls -la bin || true
          ls -la lib || true
        shell: bash

      - name: Upload artifacts (exe)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wrapper-exe-${{ matrix.arch }}
          path: bin/wrapper.exe
          if-no-files-found: warn

      - name: Upload artifacts (dll + import lib)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wrapper-dll-${{ matrix.arch }}
          path: |
            bin/wrapper.dll
            lib/wrapper.dll
            lib/wrapper.lib
          if-no-files-found: warn
